### ISSUE TITLE
Cannot convert from sql to nxd

### ISSUE THREAD

**Issue by ggdog007** [Nenkai/FF16Tools#12]
Hi,
The new function of converting from NXD to SQL works well.
But when I modified the content of the SQL database and tried to convert back to NXD file. I got below error:

> [14:15:13] [Info] Fetching table loredictionary
> [14:15:13] [Info] Loaded 1 tables from SQLite
> [14:15:13] [Info] Reading from loredictionary...
> [14:15:13] [Fatal] Unable to import from SQLite System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.String'.
>    at FF16Tools.Files.Nex.Exporters.SQLiteToNexImporter.ParseCell(NexTableLayout tableLayout, NexStructColumn column, Object val) in C:\Users\nenkai\source\repos\FF16Unpacker\FF16Tools.Files\Nex\Importers\SQLiteToNexImporter.cs:line 197
>    at FF16Tools.Files.Nex.Exporters.SQLiteToNexImporter.FillTables() in C:\Users\nenkai\source\repos\FF16Unpacker\FF16Tools.Files\Nex\Importers\SQLiteToNexImporter.cs:line 165
>    at FF16Tools.Files.Nex.Exporters.SQLiteToNexImporter.ReadSqlite() in C:\Users\nenkai\source\repos\FF16Unpacker\FF16Tools.Files\Nex\Importers\SQLiteToNexImporter.cs:line 60
>    at FF16Tools.CLI.Program.SqliteToNxd(SqliteToNxdVerbs verbs) in C:\Users\nenkai\source\repos\FF16Unpacker\FF16Tools.CLI\Program.cs:line 339

It seems certain path variables are still set to your own user directory?
Thanks,

**Comment by Nenkai** [comment]
Couldn't reproduce but tried a fix anyway. Try with 1.3.1.

**Comment by ggdog007** [comment]
It worked!
Tried replacing text in "loredictionary.nxd", loaded in the game. Other lores are not impacted. It is perfect! 
Thanks!
