### ISSUE TITLE
Won't find game data folder if game is installed on separate drive or partition

### ISSUE THREAD

**Issue by angrynewraze** [Nenkai/FF16Tools#15]
So I have my game installed on a entirely different drive than my os through steam and this tool won't find the game install folder at all let alone the game data folder.

**Comment by angrynewraze** [comment]
![Screenshot 2024-09-19 191944](https://github.com/user-attachments/assets/a8714416-f631-426c-b2fc-a532224b180f)
![Screenshot 2024-09-19 191913](https://github.com/user-attachments/assets/d8648679-4cb1-4a91-aa2b-7f914632614f)
![Screenshot 2024-09-19 191850](https://github.com/user-attachments/assets/30626afe-cdba-4e84-af3e-f4a9a058849f)
These show the errors I'm getting and my game install folder path

**Comment by Nenkai** [comment]
Surround your path with double quotes `"` since it contains spaces, otherwise tools in general have no way of parsing them.

**Comment by angrynewraze** [comment]
![Screenshot 2024-09-19 230123](https://github.com/user-attachments/assets/3b11bf45-7f08-4af5-b00e-50eef8311fd2)
I just tried the quotation marks and it still couldn't find my game install folder

**Comment by angrynewraze** [comment]
you need to fix your tool so it picks up game installs on separate drives and partitions bc right now it just doesn't do that.

**Comment by angrynewraze** [comment]
![Screenshot 2024-09-19 231844](https://github.com/user-attachments/assets/6db42f4c-7d00-4942-97a5-c2f54296bc68)
![Screenshot 2024-09-19 231759](https://github.com/user-attachments/assets/ae3c58cd-a0a6-4291-a9bb-905db76f8cef)
proof that your tool just does not pick up game installs located on a separate drive or partition

**Comment by Nenkai** [comment]
You need to point to a pack file. Not a folder.
