### ISSUE TITLE
NXD to SQL fails on floating point values on locales that use comma as decimal separator

### ISSUE THREAD

**Issue by ThisIsMyNameBecauseEverythingIsTaken** [Nenkai/FF16Tools#17]
Throws an sqlite exception "SQLite Error 1: 'all VALUES must have the same number of terms'" because the dot gets replaced by a comma and sqlite sees it as two separate values.

Quick and dirty fix is to add
`Thread.CurrentThread.CurrentCulture = System.Globalization.CultureInfo.InvariantCulture;`
to the beginning of Main.

**Comment by Nenkai** [comment]
I actually had no clue why this was happening for some users. Thanks for the tip, will be fixed for the next release

**Comment by Nenkai** [comment]
Should be solved with 1.4.0
