### ISSUE TITLE
"text" folder missing "T" in folder name

### ISSUE THREAD

**Issue by ggdog007** [Nenkai/FF16Tools#7]
Hi,
Thanks for your tool.
I test it but found a problem. If I unpack a .pac file (eg.  0001.en.pac), then pack it back to .pac file without any modification. Replace the file under game directory, launch the game, all texts are gone.
Then I unpack the same file again found the "text" foler is rename to "ext", missing a "t" in the folder name.
Can you help have a quick fix of it or any alternative solution?
Thanks,

**Comment by ggdog007** [comment]
BTW, I'm a newbie. How to launch your tool with GUI?
Thanks,

**Comment by ggdog007** [comment]
Thanks,
With your latest 1.2 release. It seems worked.

**Comment by ggdog007** [comment]
Sorry, I found the problem is still there.
For example if I unpack "0001.en.pac" and pack it back without any modification. Enter the game, all texts are gone or go wrong.
Thanks,

**Comment by Nenkai** [comment]
Can't reproduce the missing letter. What are the full commands you're running?
Make sure to provide the original archive name argument. For 0001, it should be 'nxd'.

**Comment by ggdog007** [comment]
Hi I used the command that listed in your readme.
First I launch a cmd window from where I unzip your tool, and 

FF16Tools.CLI.exe unpack-all -i D:\pac_test\0001.en.pac -o D:\pac_test

I can see a "text" folder as well as bunch of .nxd files. And I put all files and the text folder in sub-directory at D:\pac_test\en. Did no modification. Then pack them back using

FF16Tools.CLI.exe pack -i D:\pac_test\en -o 0001.en.pac

I replace the same 0001.en.pac file under game directory, launch the game, switch to English then text just go either missing or wrong.

Thanks,

**Comment by ggdog007** [comment]
> Hi I used the command that listed in your readme. First I launch a cmd window from where I unzip your tool, and
> 
> FF16Tools.CLI.exe unpack-all -i D:\pac_test\0001.en.pac -o D:\pac_test
> 
> I can see a "text" folder as well as bunch of .nxd files. And I put all files and the text folder in sub-directory at D:\pac_test\en. Did no modification. Then pack them back using
> 
> FF16Tools.CLI.exe pack -i D:\pac_test\en -o 0001.en.pac
> 
> I replace the same 0001.en.pac file under game directory, launch the game, switch to English then text just go either missing or wrong.
> 
> Thanks,

Hi I used the command that listed in your readme.
First I launch a cmd window from where I unzip your tool, and

FF16Tools.CLI.exe unpack-all -i D:\pac_test\0001.en.pac -o D:\pac_test

I can see a "text" folder as well as bunch of .nxd files. And I put all files and the text folder in sub-directory at D:\pac_test\en. Did no modification. Then pack them back using

FF16Tools.CLI.exe pack -i D:\pac_test\en -o 0001.en.pac

I replace the same 0001.en.pac file under game directory, launch the game, switch to English then text just go either missing or wrong.

Thanks,

**Comment by ggdog007** [comment]
> Can't reproduce the missing letter. What are the full commands you're running? Make sure to provide the original archive name argument. For 0001, it should be 'nxd'.

Hi I used the command that listed in your readme.
First I launch a cmd window from where I unzip your tool, and

FF16Tools.CLI.exe unpack-all -i D:\pac_test\0001.en.pac -o D:\pac_test

I can see a "text" folder as well as bunch of .nxd files. And I put all files and the text folder in sub-directory at D:\pac_test\en. Did no modification. Then pack them back using

FF16Tools.CLI.exe pack -i D:\pac_test\en -o 0001.en.pac

I replace the same 0001.en.pac file under game directory, launch the game, switch to English then text just go either missing or wrong.

Thanks,

**Comment by Nenkai** [comment]
Try again with 1.2.1, the guidelines for modding has changed a bit so read the [README](https://github.com/Nenkai/FF16Tools/blob/master/README.md) first

**Comment by ggdog007** [comment]
> Try again with 1.2.1, the guidelines for modding has changed a bit so read the [README](https://github.com/Nenkai/FF16Tools/blob/master/README.md) first

Hi, it seems worked, that I unpack and pack the .pac back, replace it under game directory, launch game, and it is normal.

But currently it seems I can do no modification to the text file. A quick test I did is
I unpack the 0001.en.pac, modify the file in "\nxd\text\levent\levent19000170.pzd". There is a dialogue at the very beginning of the demo after the opening that Clive will say "Yes, Sergent", and the branded leader will say "I said focus, Wyvern".
If I modify the line "I said focus, Wyvern" to something else like "Seeing this means mod success!"
pack the .pac and replace it under game directory and launch, continue game. I could see the leader say "Seeing this means mod success!", but the original sound of this line is muted, I heard nothing.

I also tried different speaking language, the same problem.
Further, if I did the similar to 0001.cs.pac, which is what I intend to do to have a localization of this game, both npc's dialogue line and source are disappeared.

I think it may be due to the encoding of the text file of this game. I used notepad++ to open the .pzd file. It seems it has to be utf-8 to show the dialogue text correctly in the .pzd.

My I ask if you have any suggestion on how to do text modification correctly?

Many thanks!

**Comment by ggdog007** [comment]
Sorry, I just noticed the last lines of your updated README.
So I shouldn't modify the language text file and pack, instead I should have an append file like 0001.diff.en.pac?
Would you please give an example of how to modify the text in this game? 
Much appreciated!

**Comment by ggdog007** [comment]
Hi,
Sorry to keep bothering you.
I found one interesting thing is I can modify the dialog text without loosing the npc voice only if the new string is the same length of the old one.
For example as I mentioned above, the branded leader say "I said focus, Wyvern!", if I replace it with "One two three four fi", exactly 21 characters. Then after replacing the .pac file and replay the game, the subtitle will show "One two three four fi" and the npc voice is NOT muted.
I guess there must a marker in the .pzd file or an index file to indicating the length of one dialogue string to align with the voice.
Thanks,

**Comment by Nenkai** [comment]
> Sorry, I just noticed the last lines of your updated README. So I shouldn't modify the language text file and pack, instead I should have an append file like 0001.diff.en.pac? Would you please give an example of how to modify the text in this game? Much appreciated!

Yes this is correct. Use diff files if you don't want to repack the entire folders. (by the way, thanks for the support!)

**Comment by ggdog007** [comment]
Hi,
I googled around and now I understand that when this `.pzd` file is opened as binary file, I could read the dialogue text from it only as part of it. But if I increase or decrease the length of the string, the program may break and won't load the `.pzd` correctly.
It seems it is difficult to edit the text without breaking the file. 
I just wondering is there a way to modify the game text correctly?
Thanks,

**Comment by Nenkai** [comment]
Path issues should be solved as of 1.2.2.

For the rest i'm afraid it's offtopic, you might want to ask somewhere such as [ResHax](https://reshax.com/)

**Comment by ggdog007** [comment]
Thanks,
For all your help.
Will keep checking around.
